### ISSUE TITLE
Incompatible versions in requirements.txt

### ISSUE THREAD

**Issue by svirpioj** [AaltoPML/node-BNN-covariate-shift#1]
Your `requirements.txt` does not seem to be correct. Using python3.8:

```
node-BNN-covariate-shift$ pip install -r requirements.txt
...
node-BNN-covariate-shift$ pip freeze | grep torch
torch==1.5.1
torchvision==0.6.1

node-BNN-covariate-shift$ python train_node_bnn.py
Traceback (most recent call last):
  File "train_node_bnn.py", line 20, in <module>
    from new_datasets import get_corrupt_data_loader, get_data_loader
  File "/home/svirpioj/src/node-BNN-covariate-shift/new_datasets.py", line 10, in <module>
    from tiny_imagenet import TrainTinyImageNetDataset, TestTinyImageNetDataset, CorruptTinyImageNetDataset
  File "/home/svirpioj/src/node-BNN-covariate-shift/tiny_imagenet.py", line 10, in <module>
    from torchvision.io.image import ImageReadMode, decode_image, read_image
ModuleNotFoundError: No module named 'torchvision.io.image'
```

**Comment by trungtrinh44** [comment]
Hi thank you for bringing this to my attention. I have updated the requirements.txt file.
