### ISSUE TITLE
Errors running train_node_bnn.py

### ISSUE THREAD

**Issue by svirpioj** [AaltoPML/node-BNN-covariate-shift#2]
I got a bit further with the new `requirements.txt`, but now I'm encountering other errors.

Running the script simply with defaults:

```
node-BNN-covariate-shift$ python train_node_bnn.py
INFO - experiments - Running command 'main'
INFO - experiments - Started run with ID "StoWideResNet28x10_1_cifar100_name"
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
INFO - get_logger - Train size: 45000, validation size: 5000, test size: 10000
ERROR - experiments - Failed after 0:00:02!
Traceback (most recent call last):
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "train_node_bnn.py", line 261, in main
    model, optimizer, scheduler= get_model()
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "train_node_bnn.py", line 150, in get_model
    for name, param in model.named_parameters():
UnboundLocalError: local variable 'model' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_node_bnn.py", line 250, in <module>
    def main(_run, num_train_sample, device, validation, num_epochs, logging_freq, kl_type, gamma, entropy_type, det_checkpoint, dataset, save_freq):
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 190, in automain
    self.run_commandline()
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'
```

Taking the first example in README:

```
node-BNN-covariate-shift$ python train_node_bnn.py with model_name=StoVGG16 validation=False validation_fraction=5000 augment_data=True "kl_type=upper_bound" "gamma=<GAMMA>" entropy_type=BD \
                          num_epochs=300 save_freq=301 logging_freq=1 'kl_weight.kl_min=0.0' "kl_weight.kl_max=1.0" 'kl_weight.last_iter=200' lr_ratio_det=0.01 lr_ratio_sto=1.0 \
                          prior_std=0.30 prior_mean=1.0 "det_params.weight_decay=0.0005" n_components=4 dataset=cifar10 "posterior_mean_init=(1.0,0.05)" "posterior_std_init=(0.30,0.02)" \
                          "det_params.lr=0.05" 'sto_params.lr'=0.05 'sto_params.weight_decay=0.0' "sto_params.momentum=0.0" 'sto_params.nesterov=True' 'num_train_sample'=4 bn_momentum=0.1 \
                          noise_mode=out 'sgd_params.nesterov'=True 'det_milestones=(0.50,0.90)' \
                          name=test \
                          batch_size=128 test_batch_size=512 seed=1 num_test_sample=8
WARNING - root - Changed type of config entry "gamma" from float to str
INFO - experiments - Running command 'main'
INFO - experiments - Started run with ID "StoVGG16_1_cifar10_test"
Files already downloaded and verified
...
ERROR - experiments - Failed after 0:00:02!
Traceback (most recent call last):
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "train_node_bnn.py", line 276, in main
    loss= eloglike + viw*(kl - gamma*entropy)/(n_batch*bx.size(0))
TypeError: only integer tensors of a single element can be converted to an index

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_node_bnn.py", line 250, in <module>
    def main(_run, num_train_sample, device, validation, num_epochs, logging_freq, kl_type, gamma, entropy_type, det_checkpoint, dataset, save_freq):
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 190, in automain
    self.run_commandline()
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "/home/svirpioj/.virtualenvs/node-bnn/lib/python3.8/site-packages/sacred/utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'
```

(By the way, there's `train_node_bnn.py.py` in the example commands.)

**Comment by trungtrinh44** [comment]
Hi can you put here the exact command that you use?

**Comment by svirpioj** [comment]
You can see them in the beginning of the code blocks.

**Comment by trungtrinh44** [comment]
you should replace the \<GAMMA\> with a non-negative float number.

**Comment by svirpioj** [comment]
> you should replace the <GAMMA> with a non-negative float number.

Ah, true, didn't notice that amidst the other parameters with real values. Thanks, now it started training.

And for the run without command line arguments - well, looks like there are no defaults (or sensible defaults) defined for many of the options.
